image: golang:1.12

stages:
  - dependency
  - test

variables:
  GOPATH: "${CI_PROJECT_DIR}/.go_cache"

goget:
  stage: dependency
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go_cache
  script:
    - go get

.common:
  stage: test
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .go_cache


compile:
  extends: .common
  script:
    - go build -race -ldflags "-extldflags '-static'"

lint:
  extends: .common
  script:
    - go fmt $(go list ./...)
    - go vet $(go list ./...)

test:
  extends: .common
  script:
    - go test -v -race $(go list ./...)

coverage:
  extends: .common
  script:
    - go test -race -coverprofile=coverage.txt -covermode=atomic $(go list ./...)
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN